version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: hashword
    expose:
      - 5432

  app:
    build: .
    image: app
    command: npm start
    environment:
      APP_DB_HOST: db
      APP_DB_USER: postgres
      APP_DB_PASSWORD: hashword
    expose:
      - 8000
    depends_on:
      - db

  app-test:
    image: app
    command: dockerize
        -wait tcp://db:5432 -wait tcp://app:8000 -timeout 10s
        bash -c 'node db.js && npm test'
    environment:
      APP_URL: http://app:8000
      APP_DB_HOST: db
      APP_DB_USER: postgres
      APP_DB_PASSWORD: hashword
    depends_on:
      - db
      - app
