version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: hashword
    expose:
      - 5432

  app:
    build: .
    image: app
    command: run --allow-env --allow-net main.ts
    environment:
      APP_DB_HOST: db
      APP_DB_USER: postgres
      APP_DB_PASSWORD: hashword
    expose:
      - 8000
    depends_on:
      - db

  app-test:
    image: app
    command: test --allow-env --allow-net
    environment:
      APP_URL: http://app:8000
    depends_on:
      - db
      - app
